--color=bg+:#282625,bg:#171616,spinner:#eaa4c9,hl:#96d8e3
--color=fg:#e2e0df,header:#85807a,info:#cca6e7,pointer:#eaa4c9
--color=marker:#98cdaa,fg+:#e2e0df,prompt:#96d8e3,hl+:#96d8e3
--color=selected-bg:#282625
--multi
